### ISSUE TITLE
Add a better error message for an invalid plugin.yml file

### ISSUE THREAD

**Issue by XibalbaM** [Kordify/Kordify#2]
If the plugin.yml file of a plugin is empty or missing some information, kordify crashes without proper error so it might be hard to figure out why it refuses to run.
Error for incomplete data :
```
Exception in thread "main" java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at world.anhgelus.kordify.main.plugins.PluginData$Companion.loadFromMap(PluginData.kt:20)
	at world.anhgelus.kordify.main.plugins.PluginManager.listPlugins(PluginManager.kt:62)
	at world.anhgelus.kordify.main.plugins.PluginManager.<init>(PluginManager.kt:24)
	at world.anhgelus.kordify.MainKt.main(Main.kt:30)
	at world.anhgelus.kordify.MainKt.main(Main.kt)
```
Error for empty file : 
```
Exception in thread "main" java.lang.NullPointerException: load(...) must not be null
	at world.anhgelus.kordify.main.plugins.PluginManager.listPlugins(PluginManager.kt:61)
	at world.anhgelus.kordify.main.plugins.PluginManager.<init>(PluginManager.kt:24)
	at world.anhgelus.kordify.MainKt.main(Main.kt:30)
	at world.anhgelus.kordify.MainKt.main(Main.kt)
```

**Comment by anhgelus** [comment]
Done
