### ISSUE TITLE
ClassNotFoundException for plugin main class

### ISSUE THREAD

**Issue by XibalbaM** [Kordify/Kordify#3]
# Issue
Kordify fails to load the main class of a plugin
# Steps to reproduce
- Create a Kotlin project with Gradle
- Add Kordify 0.1.0 as dependency
- Create a file called `Main.kt` in `src/main/kotlin`
- Add this content :
```kt
package fr.xibalba.kordify.messageDeletionPlugin

import net.dv8tion.jda.api.hooks.ListenerAdapter
import world.anhgelus.kordify.api.Plugin
import world.anhgelus.kordify.common.utils.Logger

class MessageDeletionPlugin : Plugin {
    override val logger = object : Logger() {
        override val name = "MessageDeletionPlugin"
    }
    override val listeners: MutableList<ListenerAdapter>
        get() = TODO("Not yet implemented")

    override fun start() {
        TODO("Not yet implemented")
    }
}
```
- Create a file called `plugin.yml` in `src/main/resources` with this content :
```kt
main: fr.xibalba.kordify.messageDeletionPlugin.MessageDeletionPlugin
author: Xibalba
version: 0.1.0
```
- Build a jar using `gardle build`
- Put the jar in `/plugins`, in the directory where Kordify.jar is located
- Run `java -jar Kordify.jar`
- Add token to `config.yml`
- Run `java -jar Kordify.jar`

# Error
```
SEVERE: Error while loading .\plugins\MessageDeletionPlugin.jar
java.lang.ClassNotFoundException: fr.xibalba.kordify.messageDeletionPlugin.MessageDeletionPlugin
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at world.anhgelus.kordify.main.plugins.PluginManager.startPlugins(PluginManager.kt:77)
	at world.anhgelus.kordify.MainKt.main(Main.kt:50)
	at world.anhgelus.kordify.MainKt.main(Main.kt)
```

# Generated jar's content 
See 
![Capture d'écran 2024-02-21 002255](https://github.com/Kordify/Kordify/assets/85184262/732ec8ed-e5ce-4b45-824d-a6e6d381e8aa)
And decompiled .class :
```kt
package fr.xibalba.kordify.messageDeletionPlugin

public final class MessageDeletionPlugin public constructor() : world.anhgelus.kordify.api.Plugin {
    public open val listeners: kotlin.collections.MutableList<net.dv8tion.jda.api.hooks.ListenerAdapter> /* compiled code */
        public open get

    public open val logger: world.anhgelus.kordify.common.utils.Logger /* compiled code */

    public open fun start(): kotlin.Unit { /* compiled code */ }
}
```

**Comment by anhgelus** [comment]
Fixed
